"""Create initial tables

Revision ID: 0259331cb8f7
Revises: 
Create Date: 2025-04-26 21:14:45.841138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0259331cb8f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheme',
    sa.Column('scheme_code', sa.Integer(), nullable=False),
    sa.Column('isin_div_payout_isin_growth', sa.String(length=16), nullable=False),
    sa.Column('isin_div_reinvestment', sa.String(length=16), nullable=False),
    sa.Column('scheme_name', sa.String(length=128), nullable=False),
    sa.Column('net_asset_value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('scheme_type', sa.String(length=32), nullable=False),
    sa.Column('scheme_category', sa.String(length=128), nullable=False),
    sa.Column('mutual_fund_family', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('scheme_code'),
    sa.UniqueConstraint('scheme_code')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=16), nullable=True),
    sa.Column('last_name', sa.String(length=16), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('portfolio_transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nav_on_purchase', sa.Float(), nullable=False),
    sa.Column('nav_now', sa.Float(), nullable=False),
    sa.Column('amount_invested', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=False),
    sa.Column('units_purchased', sa.Float(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scheme_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_code'], ['scheme.scheme_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_transaction')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('scheme')
    # ### end Alembic commands ###
